### ISSUE TITLE
FF! generates ladybug checkpoints of incorrect type

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7260]
### Current Behavior

See figure below:
![image](https://github.com/user-attachments/assets/9c214d53-ddad-4d28-bdb7-b65b7de361d9)

### Expected Behavior

Already shown above.

### Environment Information

This is ladybug frontend v0.1.0-20240805.170134, ran with a local build of the ladybug backend. FF! version info is:

**FF! 8.3.0-SNAPSHOT**: webapp 
Running on **LAPTOP-R1SK28C** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (21.0.2+13-LTS)**
Heap size: **136.0 MiB**, total JVM memory: **277.0 MiB**
Free memory: **141.0 MiB**, max memory: **1.0 GiB**
Free disk space: **123.8 GiB**, total disk space: **464.3 GiB**

**Comment by jacodg** [comment]
Result should also be outputpoint instead of inputpoint:

![image](https://github.com/user-attachments/assets/0bd57af5-ce91-4783-968c-7d356f174ad3)

**Comment by nielsm5** [comment]
IbisDebuggerAdvice uses showValue which is a inputPoint.

![image](https://github.com/user-attachments/assets/08198856-cc14-4507-9eea-59e1cf43909b)

**Comment by thomaspj10** [comment]
It seems that the problem has been solved, but be careful! I had a really hard time testing this, because I don't have access to the configuration which you used, so I could not fully reproduce it. Could you provide the configuration @mhdirkse?

**Comment by mhdirkse** [comment]
This issue is only partially solved:

![image](https://github.com/user-attachments/assets/ed3dc20e-bfed-4b97-b25e-0e4441a68454)

FF! 8.3.0-SNAPSHOT: webapp
Running on LAPTOP-R1SK28C using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 284.6 MiB, total JVM memory: 310.0 MiB
Free memory: 25.4 MiB, max memory: 1.0 GiB
Free disk space: 123.6 GiB, total disk space: 464.3 GiB
Up since: 2024-08-26 14:54:39 (22m)

This has been built locally with `ladybug/pom.xml` updated. It points to Ladybug `3.0-SNAPSHOT`. My ladybug checkout is at commit `17949903e30320233a3556c052cdf30594a68b6b`.

Ladybug-frontend version is v0.1.0-20240805.170134

**Comment by mhdirkse** [comment]
This issue can be tested with the following example configuration: https://github.com/wearefrank/ladybug/tree/master/manual-test/configurations/processXml

**Comment by thomaspj10** [comment]
The thread nodes both closing doesn't seem to be a FF bug. The JSON, which the frontend uses properly shows the opening and closing of the thread:

![image](https://github.com/user-attachments/assets/88f7bdf5-c8ec-4f7f-b0f6-f789a507e8f0)

**Comment by nielsm5** [comment]
Seems to be a ladybug frontend issue.

**Comment by mhdirkse** [comment]
I processed all answers here. Allright that this issue is now closed.
